manifest_dir = "./tmp/manifests/"

[backend]
name = "wavpack"

[backend.wavpack]
compress_options = ["--pair-unassigned-chans", "--threads=12", "-v"]
decompress_options = ["--threads=12", "-v"]

[pack]
input_paths = ["./tmp/pack-in/"]

[unpack]
input_paths = ["./tmp/unpack-in/"]
