[project]
name = "npx-compress"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sai Koukuntla", email = "sai.koukunt@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numba>=0.67.0",
    "numpy>=2.4.6",
    "pandas>=2.2.0",
    "typer>=0.27.1",
]

[project.scripts]
npx-compress = "npx_compress.main:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
